<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>anatomy</string>
    </array>
    <key>foldingStartMarker</key>
    <string>^\s*[_A-z0-9]+@.+$</string>
    <key>foldingStopMarker</key>
    <string>^.*(\])[A-z ]*\.$</string>
    <key>name</key>
    <string>Anatomy</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>begin</key>
            <string>(?&lt;!\\)(#)</string>
            <key>end</key>
            <string>\s|$|[\.,]</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.special.anatomy</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(italic):\{</string>
                    <key>end</key>
                    <string>\}</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.italic.anatomy</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_braces</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>$base</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(bold):\{</string>
                    <key>end</key>
                    <string>\}</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.bold.anatomy</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_braces</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>$base</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(verbatim|code):\{</string>
                    <key>end</key>
                    <string>\}</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.raw.anatomy</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_braces</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>$base</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(hl|atomo|example|example-segment|interaction):\{</string>
                    <key>end</key>
                    <string>\}</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_braces</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>source.atomo</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(section|title):\{</string>
                    <key>end</key>
                    <string>\}</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.heading.anatomy</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_braces</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>$base</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(underline):\{</string>
                    <key>end</key>
                    <string>\}</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.underline.anatomy</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_braces</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>$base</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(link):\{</string>
                    <key>end</key>
                    <string>\}</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.underline.link.anatomy</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_braces</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>$base</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>([[:alpha:]_!@#%&amp;*-./\?:\p{S}]+):\{</string>
                    <key>end</key>
                    <string>\}</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_braces</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>$base</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>([[:alpha:]_!@#%&amp;*-./\?:\p{S}]+):\(</string>
                    <key>end</key>
                    <string>\)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_parens</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>source.atomo</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>([[:alpha:]_!@#%&amp;*-./\?:\p{S}]+):(@\()</string>
                    <key>end</key>
                    <string>(\))</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.particle.atomo</string>
                        </dict>
                    </dict>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.particle.atomo</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>constant.other.particle.atomo</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.atomo</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>match</key>
                    <string>([[:alpha:]_!@#%&amp;*-./\?:\p{S}]+):(@([[:alpha:]_!@#%&amp;*-./\?:\p{S}]+))</string>
                    <key>end</key>
                    <string>(?=\))</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.particle.atomo</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.atomo</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>([[:alpha:]_!@#%&amp;*-./\?:\p{S}]+):\[</string>
                    <key>end</key>
                    <string>\]</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_brackets</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>source.atomo</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>match</key>
                    <string>([[:alpha:]_!@#%&amp;*-./\?:\p{S}]+)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.anatomy</string>
                        </dict>
                    </dict>
                </dict>
                <dict>
                    <key>include</key>
                    <string>source.atomo</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>match</key>
            <string>\{|\}</string>
            <key>name</key>
            <string>punctuation.section.scope.atomo</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\[|\]</string>
            <key>name</key>
            <string>punctuation.section.array.atomo</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\(|\)</string>
            <key>name</key>
            <string>punctuation.section.function.atomo</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>nest_parens</key>
        <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_parens</string>
                </dict>

                <dict>
                    <key>include</key>
                    <string>$base</string>
                </dict>
            </array>
        </dict>
        <key>nest_brackets</key>
        <dict>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\]</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_brackets</string>
                </dict>

                <dict>
                    <key>include</key>
                    <string>$base</string>
                </dict>
            </array>
        </dict>
        <key>nest_braces</key>
        <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_braces</string>
                </dict>

                <dict>
                    <key>include</key>
                    <string>$base</string>
                </dict>
            </array>
        </dict>
        <key>atomo</key>
        <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_parens</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>source.atomo</string>
                </dict>
            </array>
        </dict>
        <key>nested</key>
        <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_braces</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>$base</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.anatomy</string>
    <key>uuid</key>
    <string>A830DF80-D81B-4351-A7D5-A8AAAE66DB98</string>
</dict>
</plist>